### ISSUE TITLE
error while try to use the tool, exception occured, compatible issue!

### ISSUE THREAD

**Issue by gmg2719** [infostam/dtk-releases#1]
![image](https://github.com/user-attachments/assets/96e8be32-fa35-4840-87fb-3863e21a85e6)

**Comment by infostam** [comment]
I made a minor modification.
Could you please try the new .exe file from the URL below?
Overwrite the old .exe with this, please.

https://tiny.cc/infostam-dtk

**Comment by infostam** [comment]
Newer version of the software has been released.
